version: "3.8"

services:
  postgres: 
    image: postgres:12.15

  redis:
    image: redis:5.0.7

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
  
  rabbitmq:
    image: rabbitmq:3.11.16

  
  backend:
    container_name: reapnsow_backend
    restart: unless-stopped
    image: reapnsow_backend_img:1.0
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - redis
      - rabbitmq
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
      redsi:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  frontend:
    container_name: reapnsow_frontend
    restart: unless-stopped
    image: reapnsow_frontend_img:1.0
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend


